workflows:
  default-workflow:
    name: Build FinancnaNova
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        script: flutter test
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/**/*.apk
